spring:

  profiles:
    active: dev

  datasource:
    hikari:
      auto-commit: true
      #空闲连接超时时长
      idle-timeout: 60000
      #连接超时时长
      connection-timeout: 60000
      #最大生命周期，0不过期
      max-lifetime: 0
      #最小空闲连接数
      minimum-idle: 10
      #最大连接数量
      maximum-pool-size: 10
    type: com.zaxxer.hikari.HikariDataSource


  redis:
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 2000ms
    database: 0


  application:
    name: blog

mybatis-plus:
  type-aliases-package: com.example.blog.entity

#自定义的jwt配置
jwt:
  data:
    SECRET: dafok4DADf54a5fa1BD1dadaDA4ff5Acasda154i5
    tokenHeader: Authorization
    expiration: 604800 #7days
    tokenHead: Bearer


async:
  corePoolSize: 10
  maxPoolSize: 200
  queueCapacity: 10
