spring:

  profiles:
    active: dev

  datasource:
    hikari:
      max-lifetime: 1200000
      maximum-pool-size: 10
      connection-timeout: 300000
      minimum-idle: 5
    type: com.zaxxer.hikari.HikariDataSource

  redis:
    jedis:
      pool:
        max-idle: 1
        max-active: 8
    database: 0

  application:
    name: blog

mybatis-plus:
  type-aliases-package: com.example.blog.entity

#自定义的jwt配置
jwt:
  data:
    SECRET: dafok4DADf54a5fa1BD1dadaDA4ff5Acasda154i5
    tokenHeader: Authorization
    expiration: 604800 #7days
    tokenHead: Bearer


async:
  corePoolSize: 10
  maxPoolSize: 200
  queueCapacity: 10
